all:
	cd common;make;cd ..
	cd task;make;cd ..
	cd main;make;cd ..
	cd thread;make;cd ..
	cd command;make;cd ..
clean:
	make -f makeobj clean;
	cd common;make clean;cd ..
	cd task;make clean;cd ..
	cd main;make clean;cd ..
	cd thread;make clean;cd ..
	cd command;make clean;cd ..

